service: velo-sync-lambda-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: ap-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:PutObject
            - s3:PutObjectAcl
            - lambda:InvokeFunction
          Resource: '*'

functions:
  app:
    handler: index.handler
    name: velo-sync-lambda-app-${sls:stage}
    events:
      - httpApi:
          method: GET
          path: /status
      - httpApi:
          method: POST
          path: /s3/generate-signed-url
      - httpApi:
          method: POST
          path: /video/process

resources:
  Resources:
    VeloSyncVideoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: velo-sync-video-bucket-${sls:stage}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
              MaxAge: 3000