service: velo-sync-lambda-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: ap-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

functions:
  app:
    handler: index.handler
    name: velo-sync-lambda-app-${sls:stage}
    events:
      - httpApi:
          method: GET
          path: /status